stats_cols = [
    'possession',
    'opp_possession',
    'xg',
    'total_shots',
    'shots_on_target',
    'big_chances',
    'big_chances_missed',
    'accurate_passes',
    'accurate_passes_pc',
    'fouls_committed',
    'corners',
    'shots_off_target',
    'blocked_shots',
    'hit_woodwork',
    'shots_inside_box',
    'shots_outside_box',
    'xg_open_play',
    'xg_set_play',
    'np_xg',
    'xgot',
    'passes',
    'passes_own_half',
    'passes_opp_half',
    'accurate_long_balls',
    'accurate_long_balls_pc',
    'accurate_crosses',
    'accurate_crosses_pc',
    'throws',
    'offsides',
    'yellow_cards',
    'red_cards',
    'tackles_won',
    'tackles_won_pc',
    'interceptions',
    'blocks',
    'clearances',
    'keeper_saves',
    'duels_won',
    'ground_duels_won',
    'ground_duels_won_pc',
    'aerial_duels_won',
    'aerial_duels_won_pc',
    'successful_dribbles',
    'successful_dribbles_pc',
    'total_tackles',
    'conc_xg',
    'conc_total_shots',
    'conc_shots_on_target',
    'conc_big_chances',
    'conc_big_chances_missed',
    'conc_accurate_passes',
    'conc_accurate_passes_pc',
    'conc_fouls_committed',
    'conc_corners',
    'conc_shots_off_target',
    'conc_blocked_shots',
    'conc_hit_woodwork',
    'conc_shots_inside_box',
    'conc_shots_outside_box',
    'conc_xg_open_play',
    'conc_xg_set_play',
    'conc_np_xg',
    'conc_xgot',
    'conc_passes',
    'conc_passes_own_half',
    'conc_passes_opp_half',
    'conc_accurate_long_balls',
    'conc_accurate_long_balls_pc',
    'conc_accurate_crosses',
    'conc_accurate_crosses_pc',
    'conc_throws',
    'conc_offsides',
    'conc_yellow_cards',
    'conc_red_cards',
    'conc_tackles_won',
    'conc_tackles_won_pc',
    'conc_interceptions',
    'conc_blocks',
    'conc_clearances',
    'conc_keeper_saves',
    'conc_duels_won',
    'conc_ground_duels_won',
    'conc_ground_duels_won_pc',
    'conc_aerial_duels_won',
    'conc_aerial_duels_won_pc',
    'conc_successful_dribbles',
    'conc_successful_dribbles_pc',
    'conc_total_tackles',
    'wide_dribbles',
    'conc_wide_dribbles',
    'total_dribbles',
    'conc_total_dribbles',
    'wide_loss_of_possession',
    'conc_wide_loss_of_possession',
    'total_loss_of_possession',
    'conc_total_loss_of_possession',
    'wide_tackles_attempted',
    'conc_wide_tackles_attempted',
    'total_tackles_attempted',
    'conc_total_tackles_attempted',
    'wide_fouls',
    'conc_wide_fouls',
    'wide_clearances',
    'conc_wide_clearances',
    'wide_aerial_duels',
    'conc_wide_aerial_duels',
    'wide_blocks',
    'conc_wide_blocks',
    'pct_wide_dribbles',
    'pct_wide_loss_of_possession',
    'pct_wide_tackles_attempted',
    'pct_wide_fouls',
    'pct_wide_clearances',
    'pct_wide_aerial_duels',
    'pct_wide_blocks',
    'conc_pct_wide_dribbles',
    'conc_pct_wide_loss_of_possession',
    'conc_pct_wide_tackles_attempted',
    'conc_pct_wide_fouls',
    'conc_pct_wide_clearances',
    'conc_pct_wide_aerial_duels',
    'conc_pct_wide_blocks',
    'total_touches',
    'wide_touches',
    'wide_touches_pc',
    'conc_total_touches',
    'conc_wide_touches',
    'conc_wide_touches_pc',
]

cols_not_for_modelling = [
    'round',
    'team',
    'opp',
    'team_goals',
    'opp_goals',
    'stadium',
    'referee',
    'ref_id',
    'attendance',
    'competition',
    'division',
    'date',
    'year',
    'latitude',
    'longitude',
    'venue_href',
    'possession',
    'opp_possession',
    'xg',
    'total_shots',
    'shots_on_target',
    'big_chances',
    'big_chances_missed',
    'accurate_passes',
    'accurate_passes_pc',
    'fouls_committed',
    'corners',
    'shots_off_target',
    'blocked_shots',
    'hit_woodwork',
    'shots_inside_box',
    'shots_outside_box',
    'xg_open_play',
    'xg_set_play',
    'np_xg',
    'xgot',
    'passes',
    'passes_own_half',
    'passes_opp_half',
    'accurate_long_balls',
    'accurate_long_balls_pc',
    'accurate_crosses',
    'accurate_crosses_pc',
    'offsides',
    'yellow_cards',
    'red_cards',
    'tackles_won',
    'tackles_won_pc',
    'interceptions',
    'blocks',
    'clearances',
    'keeper_saves',
    'duels_won',
    'ground_duels_won',
    'ground_duels_won_pc',
    'aerial_duels_won',
    'aerial_duels_won_pc',
    'successful_dribbles',
    'successful_dribbles_pc',
    'total_tackles',
    'tourney_id',
    'conc_throws',
    'conc_ground_duels_won',
    'conc_xg',
    'conc_total_shots',
    'conc_shots_on_target',
    'conc_big_chances',
    'conc_big_chances_missed',
    'conc_accurate_passes',
    'conc_accurate_passes_pc',
    'conc_fouls_committed',
    'conc_corners',
    'conc_shots_off_target',
    'conc_blocked_shots',
    'conc_hit_woodwork',
    'conc_shots_inside_box',
    'conc_shots_outside_box',
    'conc_xg_open_play',
    'conc_xg_set_play',
    'conc_np_xg',
    'conc_xgot',
    'conc_passes',
    'conc_passes_own_half',
    'conc_passes_opp_half',
    'conc_accurate_long_balls',
    'conc_accurate_long_balls_pc',
    'conc_accurate_crosses',
    'conc_accurate_crosses_pc',
    'conc_offsides',
    'conc_yellow_cards',
    'conc_red_cards',
    'conc_tackles_won',
    'conc_tackles_won_pc',
    'conc_interceptions',
    'conc_blocks',
    'conc_clearances',
    'conc_keeper_saves',
    'conc_duels_won',
    'conc_throws'
    'conc_ground_duels_won',
    'conc_ground_duels_won_pc',
    'conc_aerial_duels_won',
    'conc_aerial_duels_won_pc',
    'conc_successful_dribbles',
    'conc_successful_dribbles_pc',
    'conc_total_tackles',
    'wide_dribbles',
    'conc_wide_dribbles',
    'total_dribbles',
    'conc_total_dribbles',
    'wide_loss_of_possession',
    'conc_wide_loss_of_possession',
    'total_loss_of_possession',
    'conc_total_loss_of_possession',
    'wide_tackles_attempted',
    'conc_wide_tackles_attempted',
    'total_tackles_attempted',
    'conc_total_tackles_attempted',
    'wide_fouls',
    'conc_wide_fouls',
    'wide_clearances',
    'conc_wide_clearances',
    'wide_aerial_duels',
    'conc_wide_aerial_duels',
    'wide_blocks',
    'conc_wide_blocks',
    'pct_wide_dribbles',
    'pct_wide_loss_of_possession',
    'pct_wide_tackles_attempted',
    'pct_wide_fouls',
    'pct_wide_clearances',
    'pct_wide_aerial_duels',
    'pct_wide_blocks',
    'conc_pct_wide_dribbles',
    'conc_pct_wide_loss_of_possession',
    'conc_pct_wide_tackles_attempted',
    'conc_pct_wide_fouls',
    'conc_pct_wide_clearances',
    'conc_pct_wide_aerial_duels',
    'conc_pct_wide_blocks',
    'total_touches',
    'wide_touches',
    'wide_touches_pc',
    'conc_total_touches',
    'conc_wide_touches',
    'conc_wide_touches_pc',
]

columns_to_join = [
    'wide_dribbles',
    'conc_wide_dribbles',
    'total_dribbles',
    'conc_total_dribbles',
    'wide_loss_of_possession',
    'conc_wide_loss_of_possession',
    'total_loss_of_possession',
    'conc_total_loss_of_possession',
    'wide_tackles_attempted',
    'conc_wide_tackles_attempted',
    'total_tackles_attempted',
    'conc_total_tackles_attempted',
    'wide_fouls',
    'conc_wide_fouls',
    'wide_clearances',
    'conc_wide_clearances',
    'wide_aerial_duels',
    'conc_wide_aerial_duels',
    'wide_blocks',
    'conc_wide_blocks',
    'pct_wide_dribbles',
    'pct_wide_loss_of_possession',
    'pct_wide_tackles_attempted',
    'pct_wide_fouls',
    'pct_wide_clearances',
    'pct_wide_aerial_duels',
    'pct_wide_blocks',
    'conc_pct_wide_dribbles',
    'conc_pct_wide_loss_of_possession',
    'conc_pct_wide_tackles_attempted',
    'conc_pct_wide_fouls',
    'conc_pct_wide_clearances',
    'conc_pct_wide_aerial_duels',
    'conc_pct_wide_blocks',
    'home_flag',
    'total_touches',
    'wide_touches',
    'wide_touches_pc'
]

categorical_columns = ['team_id', 'opp_id', 'referee_id', 'season']

# Mapping dictionary: key is the name in raw_data['team'], value is the corrected name
team_name_mapping = {
    'Burnley': 'Burnley',
    'Newcastle': 'Newcastle United',
    'Liverpool': 'Liverpool',
    'Wolves': 'Wolverhampton Wanderers',
    'Aston Villa': 'Aston Villa',
    'Crystal Palace': 'Crystal Palace',
    'Norwich': 'Norwich City',
    'Everton': 'Everton',
    'Leicester': 'Leicester City',
    'Man Utd': 'Manchester United',
    'Man United': 'Manchester United',
    'Brentford': 'Brentford',
    'Chelsea': 'Chelsea',
    'Watford': 'Watford',
    'Arsenal': 'Arsenal',
    'Southampton': 'Southampton',
    'Leeds': 'Leeds United',
    'Leeds Utd': 'Leeds United',
    'Man City': 'Manchester City',
    'Tottenham': 'Tottenham Hotspur',
    'Brighton': 'Brighton & Hove Albion',
    'West Ham': 'West Ham United',
    'Nottingham Forest': 'Nottingham Forest',
    'Luton': 'Luton Town',
    'Fulham': 'Fulham',
    'Sheff Utd': 'Sheffield United',
    'Sheffield Utd': 'Sheffield United',
    'Bournemouth': 'AFC Bournemouth',
    'Ipswich': 'Ipswich Town',
    'Cardiff': 'Cardiff City',
    'Hudderfield': 'Huddersfield Town',
    'West Brom': 'West Bromwich Albion',
}
